baseURL = "/"
languageCode = "en-us"
title = "Alvyl Consulting - Company Profile"
disableKinds = ["sitemap", "RSS"]
canonifyURLs = true
hideTitle = true

theme = "hugo-reveal-alvyl"

[params]
revealTheme="alvyl"

[author]
name = "Hari Krishna Ganji <hari@alvyl.com>"

[blackfriday]
hrefTargetBlank = true
